"""
Django settings for nw_fhir_demo project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

from getenv import env

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '59u(rpcheifu(1$s1s@z+gmhe(@d_j%6_^o!9g-ze#f7+#jk=e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # First Party Apps
    'apps.accounts',
    'apps.home',
    'bootstrapform',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nw_fhir_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_settings_export.settings_export',
            ],
        },
    },
]

WSGI_APPLICATION = 'nw_fhir_demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# static files and media
ASSETS_ROOT = env('DJANGO_ASSETS_ROOT', BASE_DIR)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(ASSETS_ROOT, 'collectedstatic')
MEDIA_ROOT = os.path.join(ASSETS_ROOT, 'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'sitestatic'),
]

# theme selection
THEMES = {
    0: {
        'NAME': 'Default-Readable',
        'PATH': 'theme/default/',
        'INFO': 'Readable san-serif base theme',
    },
    3: {
        'NAME': 'Readable',
        'PATH': 'theme/readable/',
        'INFO': 'Easy to read Bootswatch Theme',
    },
    4: {
        'NAME': 'Cerulean',
        'PATH': 'theme/cerulean/',
        'INFO': 'Blue Bootswatch theme theme',
    },
    5: {
        'NAME': 'Cosmo',
        'PATH': 'theme/cosmo/',
        'INFO': 'Cosmo bootswatch theme',
    },
    6: {
        'NAME': 'Cyborg',
        'PATH': 'theme/cyborg/',
        'INFO': 'Cyborg bootswatch theme',
    },
    7: {
        'NAME': 'Darkly',
        'PATH': 'theme/darkly/',
        'INFO': 'Darkly bootswatch theme',
    },
    8: {
        'NAME': 'Flatly',
        'PATH': 'theme/flatly/',
        'INFO': 'Flatly bootswatch theme',
    },
    9: {
        'NAME': 'Journal',
        'PATH': 'theme/journal/',
        'INFO': 'Journal bootswatch theme',
    },
    10: {
        'NAME': 'Lumen',
        'PATH': 'theme/lumen/',
        'INFO': 'Lumen bootswatch theme',
    },
    11: {
        'NAME': 'Paper',
        'PATH': 'theme/paper/',
        'INFO': 'Paper bootswatch theme',
    },
    12: {
        'NAME': 'Sandstone',
        'PATH': 'theme/sandstone/',
        'INFO': 'Sandstone bootswatch theme',
    },
    13: {
        'NAME': 'Simplex',
        'PATH': 'theme/simplex/',
        'INFO': 'Simplex bootswatch theme',
    },
    14: {
        'NAME': 'Slate',
        'PATH': 'theme/slate/',
        'INFO': 'Slate bootswatch theme',
    },
    15: {
        'NAME': 'Spacelab',
        'PATH': 'theme/spacelab/',
        'INFO': 'Spacelab bootswatch theme',
    },
    16: {
        'NAME': 'Superhero',
        'PATH': 'theme/superhero/',
        'INFO': 'Superhero bootswatch theme',
    },
    17: {
        'NAME': 'United',
        'PATH': 'theme/united/',
        'INFO': 'United bootswatch theme',
    },
    18: {
        'NAME': 'Yeti',
        'PATH': 'theme/yeti/',
        'INFO': 'Yeti bootswatch theme',
    },
    'SELECTED': env('DJANGO_SELECTED_THEME', 0),
}

if THEMES['SELECTED'] not in THEMES:
    THEME_SELECTED = 0
else:
    THEME_SELECTED = THEMES['SELECTED']

THEME = THEMES[THEME_SELECTED]

APPLICATION_TITLE = "Blue Button FHIR Demonstrator"

# include settings values in SETTING_EXPORT to use values in Templates.
# eg. {{ settings.APPLICATION_TITLE }}
SETTINGS_EXPORT = [
    'DEBUG',
    'APPLICATION_TITLE',
    'THEME',
    'STATIC_URL',

]
